{"uid":"15b036ebe08c2b71","name":"test_get_login_invalid_credentials","fullName":"tests.authentication.test_login#test_get_login_invalid_credentials","historyId":"32134287d0d98132759547a795aa5ea9","time":{"start":1729860012325,"stop":1729860012793,"duration":468},"status":"skipped","statusMessage":"XFAIL This test case is expected to fail due to known issue.\n\nAssertionError: Expected status code 401 but got 500. Error message: Nombre de usuario o contraseña incorrecta.","statusTrace":"get_header = {'Content-Type': 'application/json-patch+json', 'accept': '*/*'}\ninvalid_credentials = {'confirmPassword': 'invalid_password', 'password': 'invalid_password', 'username': 'invalid_username'}\n\n    @allure.suite('Log in')\n    @allure.epic('Authentication')\n    @allure.feature('Log in')\n    @allure.story('Login Invalid Credentials')\n    @allure.tag('author: Jeyson')\n    @pytest.mark.functional\n    @pytest.mark.negative\n    @pytest.mark.xfail(reason=\"This test case is expected to fail due to known issue.\",condition=True)\n    def test_get_login_invalid_credentials(get_header, invalid_credentials):\n        url = AuthenticationEndpoints.authenticate()\n        response = RealHomeRequest.post(url, get_header, invalid_credentials)\n>       assert_status_code_unauthorized(response)\n\ntests/authentication/test_login.py:65: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nresponse = <Response [500]>\n\n    def assert_status_code_unauthorized(response):\n>       assert response.status_code == 401, f\"Expected status code 401 but got {response.status_code}. Error message: {extract_error_message(response)}\"\nE       AssertionError: Expected status code 401 but got 500. Error message: Nombre de usuario o contraseña incorrecta.\n\ncore/assertions/status_code.py:14: AssertionError","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[{"name":"get_header","time":{"start":1729860009911,"stop":1729860009911,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"user_credentials","time":{"start":1729860009912,"stop":1729860009912,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"invalid_credentials","time":{"start":1729860012324,"stop":1729860012324,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false}],"afterStages":[],"labels":[{"name":"feature","value":"Log in"},{"name":"epic","value":"Authentication"},{"name":"story","value":"Login Invalid Credentials"},{"name":"tag","value":"author: Jeyson"},{"name":"suite","value":"Log in"},{"name":"tag","value":"@pytest.mark.xfail(reason='This test case is expected to fail due to known issue.', condition=True)"},{"name":"tag","value":"negative"},{"name":"tag","value":"functional"},{"name":"parentSuite","value":"tests.authentication"},{"name":"host","value":"fv-az1121-356"},{"name":"thread","value":"2236-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"tests.authentication.test_login"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[],"categories":[],"tags":["negative","functional","author: Jeyson","@pytest.mark.xfail(reason='This test case is expected to fail due to known issue.', condition=True)"]},"source":"15b036ebe08c2b71.json","parameterValues":[]}