{"uid":"467d9310f0191ce8","name":"test_get_login_empty_username_valid_password","fullName":"tests.authentication.test_login#test_get_login_empty_username_valid_password","historyId":"22923028a042fc5ddab5207e9af65f7a","time":{"start":1725907516927,"stop":1725907517596,"duration":669},"status":"skipped","statusMessage":"XFAIL This test case is expected to fail due to known issue.\n\nAssertionError: Expected status code 400 but got 500. Error message: Nombre de usuario o contraseña incorrecta.","statusTrace":"get_header = {'Content-Type': 'application/json-patch+json', 'accept': '*/*'}\nempty_username_valid_password = {'confirmPassword': 'Testing.123!', 'password': 'Testing.123!', 'username': ''}\n\n    @allure.suite('Log in')\n    @allure.epic('Authentication')\n    @allure.feature('Log in')\n    @allure.story('Login Empty Username Valid Password')\n    @allure.tag('author: Jeyson')\n    @pytest.mark.functional\n    @pytest.mark.negative\n    @pytest.mark.xfail(reason=\"This test case is expected to fail due to known issue.\",condition=True)\n    def test_get_login_empty_username_valid_password(get_header, empty_username_valid_password):\n        url = AuthenticationEndpoints.authenticate()\n        response = RealHomeRequest.post_json(url, get_header, empty_username_valid_password)\n    \n>       assert_status_bad_request(response)\n\ntests/authentication/test_login.py:136: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nresponse = <Response [500]>\n\n    def assert_status_bad_request(response):\n>       assert response.status_code == 400, f\"Expected status code 400 but got {response.status_code}. Error message: {extract_error_message(response)}\"\nE       AssertionError: Expected status code 400 but got 500. Error message: Nombre de usuario o contraseña incorrecta.\n\ncore/assertions/status_code.py:20: AssertionError","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[{"name":"user_credentials","time":{"start":1725907509667,"stop":1725907509667,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"get_header","time":{"start":1725907509667,"stop":1725907509667,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"empty_username_valid_password","time":{"start":1725907516926,"stop":1725907516926,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false}],"afterStages":[],"labels":[{"name":"story","value":"Login Empty Username Valid Password"},{"name":"suite","value":"Log in"},{"name":"tag","value":"author: Jeyson"},{"name":"feature","value":"Log in"},{"name":"epic","value":"Authentication"},{"name":"tag","value":"@pytest.mark.xfail(reason='This test case is expected to fail due to known issue.', condition=True)"},{"name":"tag","value":"negative"},{"name":"tag","value":"functional"},{"name":"parentSuite","value":"tests.authentication"},{"name":"host","value":"fv-az711-92"},{"name":"thread","value":"2146-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"tests.authentication.test_login"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[],"categories":[],"tags":["negative","functional","author: Jeyson","@pytest.mark.xfail(reason='This test case is expected to fail due to known issue.', condition=True)"]},"source":"467d9310f0191ce8.json","parameterValues":[]}