{"uid":"a54d43f83f83c946","name":"test_get_login_invalid_password","fullName":"tests.authentication.test_login#test_get_login_invalid_password","historyId":"dafeba3248b761433db3fb3d740de8c8","time":{"start":1729992366128,"stop":1729992367072,"duration":944},"status":"skipped","statusMessage":"XFAIL This test case is expected to fail due to known issue.\n\nAssertionError: Expected status code 401 but got 500. Error message: Nombre de usuario o contraseña incorrecta.","statusTrace":"get_header = {'Content-Type': 'application/json-patch+json', 'accept': '*/*'}\ninvalid_password = {'confirmPassword': 'wrong_password', 'password': 'wrong_password', 'username': 'admin'}\n\n    @allure.suite('Log in')\n    @allure.epic('Authentication')\n    @allure.feature('Log in')\n    @allure.story('Login Invalid Password')\n    @allure.tag('author: Jeyson')\n    @pytest.mark.functional\n    @pytest.mark.negative\n    @pytest.mark.xfail(reason=\"This test case is expected to fail due to known issue.\",condition=True)\n    def test_get_login_invalid_password(get_header, invalid_password):\n        url = AuthenticationEndpoints.authenticate()\n        response = RealHomeRequest.post(url, get_header, invalid_password)\n>       assert_status_code_unauthorized(response)\n\ntests/authentication/test_login.py:51: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nresponse = <Response [500]>\n\n    def assert_status_code_unauthorized(response):\n>       assert response.status_code == 401, f\"Expected status code 401 but got {response.status_code}. Error message: {extract_error_message(response)}\"\nE       AssertionError: Expected status code 401 but got 500. Error message: Nombre de usuario o contraseña incorrecta.\n\ncore/assertions/status_code.py:14: AssertionError","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[{"name":"get_header","time":{"start":1729992364674,"stop":1729992364674,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"user_credentials","time":{"start":1729992364674,"stop":1729992364674,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"invalid_password","time":{"start":1729992366128,"stop":1729992366128,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false}],"afterStages":[],"labels":[{"name":"tag","value":"author: Jeyson"},{"name":"epic","value":"Authentication"},{"name":"suite","value":"Log in"},{"name":"story","value":"Login Invalid Password"},{"name":"feature","value":"Log in"},{"name":"tag","value":"@pytest.mark.xfail(reason='This test case is expected to fail due to known issue.', condition=True)"},{"name":"tag","value":"negative"},{"name":"tag","value":"functional"},{"name":"parentSuite","value":"tests.authentication"},{"name":"host","value":"fv-az1393-92"},{"name":"thread","value":"2091-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"tests.authentication.test_login"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[],"categories":[],"tags":["negative","functional","author: Jeyson","@pytest.mark.xfail(reason='This test case is expected to fail due to known issue.', condition=True)"]},"source":"a54d43f83f83c946.json","parameterValues":[]}