{"uid":"f2fb0d88c31dadb2","name":"test_get_login_invalid_username","fullName":"tests.authentication.test_login#test_get_login_invalid_username","historyId":"9e1b11199add24c050e3cc8066e7a639","time":{"start":1726093406702,"stop":1726093407264,"duration":562},"status":"skipped","statusMessage":"XFAIL This test case is expected to fail due to known issue.\n\nAssertionError: Expected status code 401 but got 500. Error message: Nombre de usuario o contraseña incorrecta.","statusTrace":"get_header = {'Content-Type': 'application/json-patch+json', 'accept': '*/*'}\ninvalid_username = {'confirmPassword': 'Testing.123!', 'password': 'Testing.123!', 'username': 'test_invalid_user'}\n\n    @allure.suite('Log in')\n    @allure.epic('Authentication')\n    @allure.feature('Log in')\n    @allure.story('Login Invalid Username')\n    @allure.tag('author: Jeyson')\n    @pytest.mark.functional\n    @pytest.mark.negative\n    @pytest.mark.xfail(reason=\"This test case is expected to fail due to known issue.\",condition=True)\n    def test_get_login_invalid_username(get_header, invalid_username):\n        url = AuthenticationEndpoints.authenticate()\n        response = RealHomeRequest.post_json(url, get_header, invalid_username)\n>       assert_status_code_unauthorized(response)\n\ntests/authentication/test_login.py:37: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nresponse = <Response [500]>\n\n    def assert_status_code_unauthorized(response):\n>       assert response.status_code == 401, f\"Expected status code 401 but got {response.status_code}. Error message: {extract_error_message(response)}\"\nE       AssertionError: Expected status code 401 but got 500. Error message: Nombre de usuario o contraseña incorrecta.\n\ncore/assertions/status_code.py:14: AssertionError","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[{"name":"get_header","time":{"start":1726093405551,"stop":1726093405551,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"user_credentials","time":{"start":1726093405551,"stop":1726093405551,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"invalid_username","time":{"start":1726093406702,"stop":1726093406702,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false}],"afterStages":[],"labels":[{"name":"story","value":"Login Invalid Username"},{"name":"suite","value":"Log in"},{"name":"feature","value":"Log in"},{"name":"epic","value":"Authentication"},{"name":"tag","value":"author: Jeyson"},{"name":"tag","value":"@pytest.mark.xfail(reason='This test case is expected to fail due to known issue.', condition=True)"},{"name":"tag","value":"negative"},{"name":"tag","value":"functional"},{"name":"parentSuite","value":"tests.authentication"},{"name":"host","value":"fv-az732-335"},{"name":"thread","value":"2063-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"tests.authentication.test_login"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[],"categories":[],"tags":["negative","functional","author: Jeyson","@pytest.mark.xfail(reason='This test case is expected to fail due to known issue.', condition=True)"]},"source":"f2fb0d88c31dadb2.json","parameterValues":[]}